### new get
GET http://localhost:8080/artists

### create new artist
POST http://localhost:8080/artists/create
Content-Type: application/json

{
    "name": "testing artist create",
    "spotifyId": "bla bla bla",
    "popularity": 100,
    "fetchFlag": true
}

### search query artists
GET http://localhost:8080/artists/search?query=test
